### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by NoraLoose** [husseinaluie/FlowSieve#10]
I think it would be helpful for many (possibly inexperienced) users if the first step in the installation instructions would be:

- [x] To clone the FlowSieve repository (or a fork) onto the HPC system they want to use. You could also provide a link that explains how to generally clone / fork GitHub repos.

This issue is part of the JOSS review process over https://github.com/openjournals/joss-reviews/issues/4277.

**Comment by bastorer** [comment]
Good suggestion! Documentation updated accordingly.
