### ISSUE TITLE
Running the basic tutorial

### ISSUE THREAD

**Issue by NoraLoose** [husseinaluie/FlowSieve#14]
- [x] Starting from the "default" `constants.hpp`, I modified variables as in the documentation, but in addition needed to make the following modification:

```
EXTEND_DOMAIN_TO_POLES = false
```
I think it would be useful to include this in the docs too.

- [ ] It would be nice if the tutorial included the required python dependencies, e.g., for example by providing an `environment.yml` file to set up a conda environment.
- [ ] How about including a jupyter notebook that executes the steps done with python? Could be a great way to make the tutorial more interactive, and give the user some nice figures to look at and reproduce! It would only take a few lines of code to get started, e.g.,
```
import xarray as xr
ds = xr.open_dataset('/glade/u/home/noraloose/FlowSieve/Tutorial/Basic/velocity_sample.nc')
ds.uo.plot()
```
but you could also consider to make the 2 python scripts more interactive and step through them in the notebook.

This issue is part of the JOSS review process over at https://github.com/openjournals/joss-reviews/issues/4277.

**Comment by bastorer** [comment]
Making notebook versions of the tutorial python scripts is a good idea! 

I'm not very familiar with conda, but agree that giving explicit library dependencies would be helpful. I'll look into those this week.

**Comment by NoraLoose** [comment]
Let's try to work toward closing this issue. 

- [ ] I'll leave it up to you if you want to include a jupyter notebook for this tutorial or not.
- [ ] But I think providing an `environment.yml` for the required python dependencies (for all tutorials together, so I would place it [here](https://github.com/husseinaluie/FlowSieve/tree/master/Tutorial) with some instructions) would be very helpful - then I can also tick off the following reviewer box :) 
```
Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
```

**Comment by bastorer** [comment]
Notebook added :-)

I've added an environment file listing the versions that I used why I ran the tutorials. I'm not very familiar with .yml files, but I *think* I've got it formatted correctly.

**Comment by NoraLoose** [comment]
You can check whether your conda environment works correctly by following the steps [here](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file). 
* A quick test tells me that `cmocean` is missing in the `environment.yml` file. There may be other packages missing. Could you check if all tutorials are running after activating the `FlowSieve-tutorial-env` environment? Thanks!
* It would be great if you could add instructions to https://github.com/husseinaluie/FlowSieve/blob/master/Tutorial/TUTORIAL.md on how to create and activate the conda environment before running any of the tutorials.

**Comment by bastorer** [comment]
I've got the conda environment working on the other server :-) I'm having some trouble getting it to play nice when I try to activate the environment inside of submitted jobs, but otherwise running in command-line in the activated environment reproduces the tutorial figures

**Comment by bastorer** [comment]
Hi Nora,

With the environment.yml and jupyter notebooks set up, is there anything else that you think needs to be addressed for this ticket?

Thanks!

**Comment by NoraLoose** [comment]
Cool, I just tested the conda environment, and am able to run all python scripts. Closing this issue!
