### ISSUE TITLE
What variables can be coarse grained by FlowSieve?

### ISSUE THREAD

**Issue by NoraLoose** [husseinaluie/FlowSieve#16]
Is FlowSieve specialized in coarse-graining velocity fields? Or can you also coarse-grain tracer fields? 

I think these are questions that many potential users will have. It would be great if 1-2 clarifying sentences can be included in the paper & documentation.

https://github.com/openjournals/joss-reviews/issues/4277

**Comment by bastorer** [comment]
FlowSieve can coarse-grain any scalar fields, and can nominally process any vector field as well, provided that it first be passed through the Helmholtz projection step.

A lot / most of the diagnostic outputs are built around filtering velocity, but we've also filtered density fields using the `coarse_grain_scalar.x` case file.

Good suggestion about the clarifying sentences! I'll add those.

**Comment by NoraLoose** [comment]
Gotcha! Could be nice to illustrate the filtering of a scalar field as part of the basic tutorial as well. I know tons of people who want to filter scalar fields - so having an example for scalar fields in the tutorial could attract more users! 😃

**Comment by bastorer** [comment]
Good point! I'll work on giving the Tutorials section (and documentation) a bit of an overhaul this week.

**Comment by bastorer** [comment]
@NoraLoose the scalars tutorial has been added and the documentation and paper includes the line

> computes coarse-grained scalar and vector fields for arbitrary filter scales, in both Cartesian and spherical coordinates

in the core features  section.

**Comment by NoraLoose** [comment]
Great, thanks for adding these clarifications and the tutorial! I'm closing this issue.
