### ISSUE TITLE
Scalar Tutorial

### ISSUE THREAD

**Issue by NoraLoose** [husseinaluie/FlowSieve#19]
Just two quick questions regarding the "Scalar Tutorial":

- [x]  Is [FiniteDiff.py](https://github.com/husseinaluie/FlowSieve/blob/master/Tutorial/Scalars/FiniteDiff.py) needed for the tutorial?
- [x]  Is [submit_filtering.sh](https://github.com/husseinaluie/FlowSieve/blob/master/Tutorial/Scalars/submit_filtering.sh) up to date? It specifies to filter a file `velocity_sample.nc`.

Tagging https://github.com/openjournals/joss-reviews/issues/4277

**Comment by bastorer** [comment]
Thanks for catching those. FiniteDiff was not needed (and has been removed) and the submit script has been updated to match the run_all_steps script :-)

**Comment by bastorer** [comment]
Good idea, I've added the figure :-)

**Comment by NoraLoose** [comment]
Cool, I am closing this issue.
