### ISSUE TITLE
Add a copy of `constants.hpp` with the specific values in Tutorials

### ISSUE THREAD

**Issue by ashwinvis** [husseinaluie/FlowSieve#28]
This is not a bug, but a suggestion. The number of parameters to go around and edit manually to get through the tutorial is a lot and I had to change it for every tutorial.

I think a new user would be best served by a copy of the `constants.hpp` file. Ther may also be other solutions to quickly get started

**Comment by bastorer** [comment]
That's an excellent suggestion. Having a `constants.hpp` file in each tutorial, as well as a couple constants file for typical use cases would help soften the learning curve for using FlowSieve. I'll make those this week :-)

**Comment by ashwinvis** [comment]
Thanks! It looks good.
