### ISSUE TITLE
Example of usage with MPI parallelism

### ISSUE THREAD

**Issue by ashwinvis** [husseinaluie/FlowSieve#29]
While in the article you state that

> In particular, MPI is used to divide time and depth

I did not find an example which demonstrates this in the Tutorials. We only see OpenMP being used and `SLURM_NTASKS` is always set as 1. Would it be possible to construct a simple example which shows MPI parallelism. This is necessary to check out from https://github.com/openjournals/joss-reviews/issues/4277#issuecomment-1383020819:

> Functionality: Have the functional claims of the software been confirmed?

**Comment by bastorer** [comment]
It hadn't even occurred to me that I didn't have any MPI tutorials. Thanks for point that out! I'll fix that this week :-)

**Comment by ashwinvis** [comment]
40 processors is a bit much, so I have to get a supercomputer to test it. Would it be possible to reduce the requirements such that even with 8 processors you get something in a few minutes?

**Comment by bastorer** [comment]
For something that runs in ~5 minutes on 8 processors, setting the number of vertical levels to 8 (last number on line 13 of `generate_data_sphere.py`, change from 48 to 8) should do the trick.

**Comment by ashwinvis** [comment]
Managed to run with 8 vertical levels and 4 processors in a laptop for ~30 minutes.
