### ISSUE TITLE
How to make an appropriate system.mk file

### ISSUE THREAD

**Issue by Broccoliedee** [husseinaluie/FlowSieve#32]
Hi!
I am new here! I don't know how to compile Case_files/coarse_grain.x. Should I make a system.mk file before compiling?
It's grateful to have your suggestions!

**Comment by bastorer** [comment]
Hi :-)

Yep, the first step is to get a `system.mk` file set up. You should only need to do this once, and after that you should be able to compile.

There are a couple sample `system.mk` files in the `Systems/` directory. The main parts are to specify what compilers you're using (`CXX` and `MPICXX`, e.g. `icpc` and `mpiicpc` for intel compilers), and possibly needing to specify where some libraries are (e.g. pointing to the NETCDF library).

Hope that helps, and feel free to ask more questions!

**Comment by bastorer** [comment]
I'm going to go ahead and close this ticket. Feel free to re-open or start a new ticket if you want to come back to it.
