### ISSUE TITLE
OSI approved license

### ISSUE THREAD

**Issue by NoraLoose** [husseinaluie/FlowSieve#5]
JOSS requires the LICENSE file to have the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license. I can't find the ODC-BY 1.0 license among the licenses in the OSI approved list. 

This issue is part of the JOSS review process over [here](https://github.com/openjournals/joss-reviews/issues/4277).

**Comment by bastorer** [comment]
License has been changed to the Open Software License 3 (OLS-3.0, https://opensource.org/licenses/OSL-3.0)

**Comment by NoraLoose** [comment]
Thanks! I will close this issue.

**Comment by NoraLoose** [comment]
Sorry, will re-open this because I found an inconsistency regarding the license: In the documentation it says you use the ODC-BY 1.0 license. Should be an easy fix to change it to OSL-3.0!

**Comment by NoraLoose** [comment]
It still shows up as ODC-BY 1.0 for me:
![Screen Shot 2022-09-05 at 7 48 55 AM](https://user-images.githubusercontent.com/23617395/188464604-a1efa49e-88b0-4cef-991a-2fbb10a4e44e.png)

**Comment by bastorer** [comment]
Oh, sorry, I forgot to rebuild the ReadTheDocs after that push ( I haven't quite figured out how to get the web hook set up to auto-rebuild the docs. I'll try to sort that out this week. ).
You might need to view it in a 'private' browser [ I've found browser caching to be a headache haha, so if you know any good tricks around that when developing documentation, I'd love to hear them! ]
