### ISSUE TITLE
Documentation: Methods

### ISSUE THREAD

**Issue by NoraLoose** [husseinaluie/FlowSieve#6]
There are a few inconsistencies and typos in the method section of the documentation, and it would be helpful to give it a bit more structure (via section headers). Specifically:

- [x] Two different version of phi are used interchangeably. It would make the documentation clearer to stick to only one of the 2 symbols.
- [x] What is "L_pad"?
- [x]  "currently implementation" --> "current implementation"
- [x] "An identical equation":  identical to what? It may be clearer to label the equation for Delta phi_N above, and than you could write: "An identical equation to [labeled equation]".
- [x] Before writing down the large-scale KE budget, it may be helpful to start a new section with a new section header, e.g.,  "Large-scale KE budget". It would also be helpful to refer the user to e.g., Aluie et al. (2018) for the derivation.
- [x] New section header before you introduce the Lamba^m equation.
- [x] It would be helpful to introduce a new section header before the sentence "This section outlines some of the parallelizations that are used.", e.g., "Parallelizing computations"
- [x] reoutines --> routines

This issue is part of the JOSS review process over https://github.com/openjournals/joss-reviews/issues/4277.

**Comment by bastorer** [comment]
Thanks for the feedback! It looks like there was a silent cascading error with header rendering that made the documentation much harder to read. This should now be resolved and much more user-friendly.

**Comment by NoraLoose** [comment]
I agree - this looks much more user-friendly now! :)

While reading through the documentation, I spotted a few further minor typos (not all in the Methods sections):

- [ ] consants --> constants on https://flowsieve.readthedocs.io/en/latest/constants_8hpp.html
- [ ] reach --> reached on https://flowsieve.readthedocs.io/en/latest/helmholtz1.html
- [ ] "Coarsen the to" --> "Coarsen to" on https://flowsieve.readthedocs.io/en/latest/helmholtz1.html

**Comment by bastorer** [comment]
Typos corrected :-)

**Comment by bastorer** [comment]
Also, I've added a `--help` flag to the executables that gives users more details about the command-line arguments that can be passed at runtime.

<img width="950" alt="Help flag" src="https://user-images.githubusercontent.com/8304555/199826714-e610262b-7758-495b-94f9-81ed4e37debb.png">
