### ISSUE TITLE
Documentation: Tree structure

### ISSUE THREAD

**Issue by NoraLoose** [husseinaluie/FlowSieve#7]
There is something funky going on with the documentation tree. The red circled parts don't seem to be actual subsections of the "Installation" section (but rather belong to the License text etc.).

<img width="553" alt="Screen Shot 2022-04-15 at 12 22 24 PM" src="https://user-images.githubusercontent.com/23617395/163607034-db6c4353-f436-4fd0-916d-92b5bc9f3b74.png">
 
This issue is part of the JOSS review process over https://github.com/openjournals/joss-reviews/issues/4277.

**Comment by bastorer** [comment]
I managed to hunt down the silent cascading error that caused this, so the tree structure should now resemble the actual documentation structure!

**Comment by husseinaluie** [comment]
Hi Ben,

What are the next steps with the JOSS paper? Is everything done and
awaiting approval from the "editor"? Or will it go back to the reviewers
for another round?

Thanks,
Hussein



Hussein Aluie (he/him)
Associate Professor
Department of Mechanical Engineering
University of Rochester
Office: 585-276-7170
Cell: 410-340-3145
http://www.me.rochester.edu/~haluie/

**Comment by NoraLoose** [comment]
Looks good now!
