### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by NoraLoose** [husseinaluie/FlowSieve#8]
JOSS asks to include 
> clear community guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support.

Could you please add community guidelines to this effect? I think the README would be a great place for that.

This issue is part of the JOSS review process over https://github.com/openjournals/joss-reviews/issues/4277.

**Comment by bastorer** [comment]
Community guidelines are now part of the readme and the documentation landing page

**Comment by NoraLoose** [comment]
Thanks for adding these guidelines! When you mention the GitHub issue tracking tools, you could add a link to https://github.com/husseinaluie/FlowSieve/issues.
