### ISSUE TITLE
Software paper

### ISSUE THREAD

**Issue by NoraLoose** [husseinaluie/FlowSieve#9]
JOSS requires the software paper to include the following elements:

- [x] **Summary** of software: While your summary section is a great motivation for why coarse graining is needed, it does not describe the high-level functionality and purpose of the **software** (but rather of the technique coarse graining in general). Could you adapt the summary to be more specific to the software package FlowSieve?
- [ ] **State of the field**: Could you include a discussion on how FlowSieve compares to other commonly-used packages?

This issue is part of the JOSS review process over https://github.com/openjournals/joss-reviews/issues/4277.

**Comment by bastorer** [comment]
I've updated the paper with "Summary of Software" and "State of the Field" sections added.

**Comment by NoraLoose** [comment]
Thanks for adding these sections! I think they will really help the reader understand better what FlowSieve is all about.

It would be nice if you could add a citation for the GCM-Filters package. :)

**Comment by bastorer** [comment]
Absolutely, I'm not sure why I didn't include the reference to begin with, sorry!

I've now included a reference to GCM-Filters, as well as a reference to the structure function approach ( via Dhruv's cascade paper on arxiv ).

**Comment by bastorer** [comment]
Thanks for pointing those out. Paper references have been updated accordingly.
